# This workflow only runs when it is manually dispatched using GitHub.
# It does a dry-run of publishing this project to the ESP component registry.
# The project won't actually be published.

name: Dry-run ESP-IDF component upload.
on:
  workflow_dispatch:

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Dry-run upload to the ESP component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          dry_run: True
          name: "libcanard"
          version: ${{ github.event.release.tag_name }}
          namespace: "opencyphal"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
